{-
  Generated by 'genRules' (automatic rule generation for DrIFT). Don't touch!!
  dependency files: COL/AS_COL.hs COL/COLSign.hs
-}

module COL.ATC_COL where

import Common.ATerm.Lib
import COL.AS_COL
import Common.Id
import Common.AS_Annotation
import CASL.AS_Basic_CASL
import CASL.ATC_CASL
import Modal.ModalSign
import CASL.Sign
import qualified Common.Lib.Map as Map
import qualified Common.Lib.Set as Set
import ATC.Id
import ATC.AS_Annotation


{-! for COL_SIG_ITEM derive : ShATermConvertible !-}
{-! for ModalSign derive : ShATermConvertible !-}

