-- do not edit; automatically generated by UU_AG
module ErrorMessages where

import UU_Pretty
import UU_Pretty_ext
import CommonTypes
import TokenDef(Pos)
-- Error -------------------------------------------------------
data Error = CustomError (PP_Doc)
           | DupAlt (Pos) (Pos) (Nonterminal) (Constructor)
           | DupChild (Pos) (Pos) (Nonterminal) (Constructor) (Name)
           | DupInhAttr (Pos) (Pos) (Nonterminal) (Name)
           | DupLocal (Nonterminal) (Constructor) (Name)
           | DupRule (Pos) (Pos) (Nonterminal) (Constructor) (Name) (Name)
           | DupSynAttr (Pos) (Pos) (Nonterminal) (Name)
           | DupSynonym (Pos) (Pos) (Nonterminal)
           | MissingRule (Nonterminal) (Constructor) (Name) (Name)
           | NameClash (Pos) (Pos) (Nonterminal) (Constructor) (Name)
           | SuperfluousRule (Pos) (Nonterminal) (Constructor) (Name) (Name)
           | UndefAlt (Pos) (Nonterminal) (Constructor)
           | UndefAttr (Pos) (Nonterminal) (Constructor) (Name) (String)
           | UndefChild (Pos) (Nonterminal) (Constructor) (Name)
           | UndefLocal (Pos) (Nonterminal) (Constructor) (String)
           | UndefNont (Pos) (Nonterminal)
-- Errors ------------------------------------------------------
type Errors = [(Error)]

