-- do not edit; automatically generated by UU_AG
module Expression where

import TokenDef(Pos)
-- Expression --------------------------------------------------
data Expression = Expression (Pos) (String)

