{-# OPTIONS -w -O0 #-}
{- |
Module      :  EVT/ATC_EVT.der.hs
Description :  generated ShATermConvertible instances
Copyright   :  (c) DFKI GmbH 2012
License     :  GPLv2 or higher, see LICENSE.txt

Maintainer  :  Christian.Maeder@dfki.de
Stability   :  provisional
Portability :  non-portable(derive Typeable instances)

Automatic derivation of instances via DrIFT-rule ShATermConvertible
  for the type(s):
'EVT.AS.MACHINE'
'EVT.AS.EVENT'
'EVT.AS.GUARD'
'EVT.AS.ACTION'
'EVT.AS.EVTQualId'
'EVT.Sign.EVTSign'
'EVT.Sign.EVTMorphism'
'EVT.Sign.EVTDatatype'
'EVT.Sign.EVTSymbol'
-}

{-
Generated by 'genRules' (automatic rule generation for DrIFT). Don't touch!!
  dependency files:
EVT/AS.hs
EVT/Sign.hs
-}

module EVT.ATC_EVT () where

import ATC.GlobalAnnotations
import ATerm.Lib
import CASL.AS_Basic_CASL
import CASL.ATC_CASL ()
import Common.Id
import Data.Data
import EVT.AS
import EVT.Sign
import qualified Data.Map as Map

{-! for EVT.AS.MACHINE derive : ShATermConvertible !-}
{-! for EVT.AS.EVENT derive : ShATermConvertible !-}
{-! for EVT.AS.GUARD derive : ShATermConvertible !-}
{-! for EVT.AS.ACTION derive : ShATermConvertible !-}
{-! for EVT.AS.EVTQualId derive : ShATermConvertible !-}
{-! for EVT.Sign.EVTSign derive : ShATermConvertible !-}
{-! for EVT.Sign.EVTMorphism derive : ShATermConvertible !-}
{-! for EVT.Sign.EVTDatatype derive : ShATermConvertible !-}
{-! for EVT.Sign.EVTSymbol derive : ShATermConvertible !-}
