#!/bin/bash

# A sample application using the OWL API. 

# Class path
SEPARATOR=":"
# LIBHOME="/home/luettich/CASL/owlapi-1.4.0-WonderWeb/pellet-1.1.0/lib/"
#OWLAPI="econn-owlapi"
#JUNIT="junit"

cd $HETS_OWL_PARSER/java
LIBHOME="./jlib"
CLASSPATH=
for x in $LIBHOME/*.jar 
do
  CLASSPATH=$CLASSPATH$SEPARATOR$x
done

#CLASSPATH=$CLASSPATH:$LIBHOME$JUNIT/junit.jar:$LIBHOME/aterm-java-1.6.jar:$LIBHOME/log4j-1.2.7.jar:$LIBHOME/pellet.jar

java -cp $CLASSPATH:./OWLParser.jar OWL2ATerm $* || exit $?
mv output.term ../
cd -
