#!/bin/bash
read -s -n1 -p "Do you want to build all containers? (y/n)[n] " input
case $input in
  [yY])
    echo 'Building docker containers...'
    docker-compose build
    echo '' ;;
  ""|[nN])
    echo '' ;;
  *)
    echo "Invalid input..."
    exit 1;;
esac

echo 'Starting docker containers...'
docker-compose up -d
