#!/bin/bash

# A sample application using the OWL API. 

cd $HETS_OWL_TOOLS
java -Djava.library.path=lib/native/`uname -m` -jar $HETS_OWL_TOOLS/OWLFact.jar $* || exit $?   
# mv output.term $HETS_OWL_TOOLS
# cd -
