#!/bin/bash
hetsdir=`dirname "$0"`
export PATH=$hetsdir/uDrawGraph-3.1/bin:$PATH
export HETS_LIB=$hetsdir/Hets-lib
export HETS_OWL_TOOLS=$hetsdir/hets-owl-tools
export HETS_APROVE=$HETS_OWL_TOOLS/AProVE.jar
export HETS_ONTODMU=$HETS_OWL_TOOLS/OntoDMU.jar
export PELLET_PATH=$hetsdir/pellet
export HETS_MAGIC=$HETS_OWL_TOOLS/hets.magic
"$hetsdir/hets" "$@"
