{-# OPTIONS -fno-warn-unused-imports #-}
{- |
Module      :  OWL_DL/OWL11/ATC_OWL11.der.hs
Description :  generated Typeable, ShATermConvertible instances
Copyright   :  (c) Uni Bremen 2005
License     :  similar to LGPL, see HetCATS/LICENSE.txt

Maintainer  :  Christian.Maeder@dfki.de
Stability   :  provisional
Portability :  non-portable(overlapping Typeable instances)

Automatic derivation of instances via DrIFT-rule Typeable, ShATermConvertible
  for the type(s):
'OWL_DL.OWL11.Sign.Sign'
'OWL_DL.OWL11.Sign.SignAxiom'
'OWL_DL.OWL11.Sign.RoleType'
'OWL_DL.OWL11.Sign.RDomain'
'OWL_DL.OWL11.Sign.RRange'
'OWL_DL.OWL11.Sign.Sentence'
-}
{-
  Generated by 'genRules' (automatic rule generation for DrIFT). Don't touch!!
  dependency files:
OWL_DL/OWL11/Sign.hs
-}

module OWL_DL.OWL11.ATC_OWL11 where

import OWL_DL.OWL11.Sign
import OWL_DL.OWL11.FFS
import qualified Data.Set as Set
import qualified Data.Map as Map
import Data.Typeable
import Common.ATerm.Lib
import ATC.AS_Annotation
import OWL_DL.OWL11.ReadWrite

{-! for OWL_DL.OWL11.Sign.Sign derive : Typeable !-}
{-! for OWL_DL.OWL11.Sign.SignAxiom derive : Typeable !-}
{-! for OWL_DL.OWL11.Sign.RoleType derive : Typeable !-}
{-! for OWL_DL.OWL11.Sign.RDomain derive : Typeable !-}
{-! for OWL_DL.OWL11.Sign.RRange derive : Typeable !-}
{-! for OWL_DL.OWL11.Sign.Sentence derive : Typeable !-}

{-! for OWL_DL.OWL11.Sign.Sign derive : ShATermConvertible !-}
{-! for OWL_DL.OWL11.Sign.SignAxiom derive : ShATermConvertible !-}
{-! for OWL_DL.OWL11.Sign.RoleType derive : ShATermConvertible !-}
{-! for OWL_DL.OWL11.Sign.RDomain derive : ShATermConvertible !-}
{-! for OWL_DL.OWL11.Sign.RRange derive : ShATermConvertible !-}
{-! for OWL_DL.OWL11.Sign.Sentence derive : ShATermConvertible !-}
