#!/bin/bash

# A sample application using the OWL API. 

## cd $HETS_OWL_PARSER
rm output.term 2>/dev/null
java -jar $HETS_OWL_PARSER/OWL11/OWL2ATerm.jar $* || exit $?   
# mv output.term $HETS_OWL_PARSER
# cd -
