# NB.  Although this package is contained in the MMiSS directory, it should
# be compiled before it; this is done by getting the main uni Makefile
# to refer to it directly.
PACKAGES = fgl
PACKAGE = Main

SRCS =  test.hs 

include /home/amahnke/uni/mk/boilerplate.mk
