{-# OPTIONS -w -O0 #-}
{-# LANGUAGE StandaloneDeriving, DeriveDataTypeable #-}
{- |
Module      :  QVTR/ATC_QVTR.der.hs
Description :  generated Typeable, ShATermConvertible instances
Copyright   :  (c) DFKI GmbH 2012
License     :  GPLv2 or higher, see LICENSE.txt

Maintainer  :  Christian.Maeder@dfki.de
Stability   :  provisional
Portability :  non-portable(derive Typeable instances)

Automatic derivation of instances via DrIFT-rule Typeable, ShATermConvertible
  for the type(s):
'QVTR.As.Transformation'
'QVTR.As.Key'
'QVTR.As.PropKey'
'QVTR.As.Relation'
'QVTR.As.RelVar'
'QVTR.As.PrimitiveDomain'
'QVTR.As.Domain'
'QVTR.As.ObjectTemplate'
'QVTR.As.PropertyTemplate'
'QVTR.As.WhenWhere'
'QVTR.As.RelInvok'
'QVTR.As.OCL'
'QVTR.As.STRING'
'QVTR.Sign.RuleDef'
'QVTR.Sign.Sign'
'QVTR.Sign.Sen'
'QVTR.Sign.RelationSen'
'QVTR.Sign.Pattern'
-}

{-
Generated by 'genRules' (automatic rule generation for DrIFT). Don't touch!!
  dependency files:
QVTR/As.hs
QVTR/Sign.hs
-}

module QVTR.ATC_QVTR () where

import ATerm.Lib
import CSMOF.Print ()
import Common.ATerm.ConvInstances
import Common.Doc
import Common.DocUtils
import Common.Id
import Data.Typeable
import QVTR.As
import QVTR.Print ()
import QVTR.Sign
import qualified CSMOF.As as CSMOF
import qualified CSMOF.Sign as CSMOF
import qualified Data.Map as Map

{-! for QVTR.As.Transformation derive : Typeable !-}
{-! for QVTR.As.Key derive : Typeable !-}
{-! for QVTR.As.PropKey derive : Typeable !-}
{-! for QVTR.As.Relation derive : Typeable !-}
{-! for QVTR.As.RelVar derive : Typeable !-}
{-! for QVTR.As.PrimitiveDomain derive : Typeable !-}
{-! for QVTR.As.Domain derive : Typeable !-}
{-! for QVTR.As.ObjectTemplate derive : Typeable !-}
{-! for QVTR.As.PropertyTemplate derive : Typeable !-}
{-! for QVTR.As.WhenWhere derive : Typeable !-}
{-! for QVTR.As.RelInvok derive : Typeable !-}
{-! for QVTR.As.OCL derive : Typeable !-}
{-! for QVTR.As.STRING derive : Typeable !-}
{-! for QVTR.Sign.RuleDef derive : Typeable !-}
{-! for QVTR.Sign.Sign derive : Typeable !-}
{-! for QVTR.Sign.Sen derive : Typeable !-}
{-! for QVTR.Sign.RelationSen derive : Typeable !-}
{-! for QVTR.Sign.Pattern derive : Typeable !-}

{-! for QVTR.As.Transformation derive : ShATermConvertible !-}
{-! for QVTR.As.Key derive : ShATermConvertible !-}
{-! for QVTR.As.PropKey derive : ShATermConvertible !-}
{-! for QVTR.As.Relation derive : ShATermConvertible !-}
{-! for QVTR.As.RelVar derive : ShATermConvertible !-}
{-! for QVTR.As.PrimitiveDomain derive : ShATermConvertible !-}
{-! for QVTR.As.Domain derive : ShATermConvertible !-}
{-! for QVTR.As.ObjectTemplate derive : ShATermConvertible !-}
{-! for QVTR.As.PropertyTemplate derive : ShATermConvertible !-}
{-! for QVTR.As.WhenWhere derive : ShATermConvertible !-}
{-! for QVTR.As.RelInvok derive : ShATermConvertible !-}
{-! for QVTR.As.OCL derive : ShATermConvertible !-}
{-! for QVTR.As.STRING derive : ShATermConvertible !-}
{-! for QVTR.Sign.RuleDef derive : ShATermConvertible !-}
{-! for QVTR.Sign.Sign derive : ShATermConvertible !-}
{-! for QVTR.Sign.Sen derive : ShATermConvertible !-}
{-! for QVTR.Sign.RelationSen derive : ShATermConvertible !-}
{-! for QVTR.Sign.Pattern derive : ShATermConvertible !-}
