default: k kd cl gml pml hm
main:
	cd ..; make; make clean
k:
	cd scripts; ./checkK.sh
kd:
	cd scripts; ./checkKD.sh
cl:
	cd scripts; ./checkC.sh
gml:
	cd scripts; ./checkG.sh
pml:
	cd scripts; ./checkP.sh
hm:
	cd scripts; ./checkHM.sh
mon: 
	cd scripts; ./checkMon.sh
