#!/usr/local/bin/perl

use strict;
use File::Basename;

my $un=`uname`;
my $suf = 'unknown';
my $haddocklib = 'utils/hd-lib';

$un =~ m"^SunOS" && do {$suf = "solaris"};    
$un =~ m"^Linux" && do {$suf = "linux"};

if($suf eq 'unknown') {
    print STDERR "Unknown system\nSupported systems: solaris (SunOS), Linux\n";
    exit 1;
}

if ($suf eq 'linux') {
    my $tmp = $ENV{'LD_LIBRARY_PATH'} if exists $ENV{'LD_LIBRARY_PATH'};
    if (defined $tmp) {
	$ENV{'LD_LIBRARY_PATH'} = "$tmp:/usr/local/lib";
    } else {
	$ENV{'LD_LIBRARY_PATH'} = "/usr/local/lib";
    }
}

# for documentation purposes the copy of haddocks startup-script:
# #!/bin/sh
# HADDOCKLIB="/home.local/luettich/haddock-0.4/haddock/html";
# HADDOCKBIN="/home.local/luettich/haddock-0.4/haddock/src/haddock.bin";
# # Mini-driver for Haddock

# # needs the following variables:
# #       HADDOCKLIB
# #       HADDOCKBIN

# $HADDOCKBIN --lib $HADDOCKLIB ${1+"$@"}

exec("$0.$suf",'--lib',$haddocklib,@ARGV);
print STDERR 'couldn\'t exec "',"$0.$suf","\"\n";
exit 2;
