#!/bin/sh

# A sample application using the OWL API. 

# Class path
SEPARATOR=":"
LIBHOME="/home/luettich/CASL/owlapi-1.4.0-WonderWeb/pellet-1.1.0/lib/"
OWLAPI="econn-owlapi"
JUNIT="junit"

CLASSPATH=
for x in $LIBHOME$OWLAPI/*.jar 
do
  CLASSPATH=$CLASSPATH$SEPARATOR$x
done
CLASSPATH=$CLASSPATH:$LIBHOME$JUNIT/junit.jar:$LIBHOME/aterm-java-1.6.jar:$LIBHOME/log4j-1.2.7.jar:$LIBHOME/pellet.jar

java -cp $CLASSPATH OWL2ATerm $*
      
