test: k kd cl gml gen
#	cd ..; make clean
main:
	cd ..; make
k:
	cd scripts; ./checkK.sh
kd:
	cd scripts; ./checkKD.sh
cl:
	cd scripts; ./checkCL.sh
gml:
	cd scripts; ./checkGML.sh
ml:
	cd scripts; ./checkML.sh
gen:
	cd scripts; ./checkGen.sh
